language: java

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
  - $HOME/.m2

sudo: false

install: true

script:
  - mvn -f spring-boot-current/pom.xml clean test
  - mvn -f spring-boot-current/pom.xml -Psnapshot clean test
  - mvn -f spring-boot-current/pom.xml -Pcurrent-ogm-matching clean test
  - mvn -f spring-boot-next/pom.xml clean test
  - mvn -f spring-boot-next/pom.xml -Psnapshot clean test
